on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - run: |
        cd unity/main/Assets/com.andtech.augment
        npm version ${{github.ref_name}} --allow-same-version
    - uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: upm
        FOLDER: unity/main/Assets/com.andtech.augment
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
